name: 'Destroy'
on:
  workflow_dispatch

env:
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: "eu-central-1"

jobs:
  switch:
    name: 'Destroy'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
        
      - name: Setup Terragrunt
        uses: peter-murray/terragrunt-github-action@v1.0.0
        with:
          terragrunt_version: 0.39.0
      
      - name: Interact with Terragrunt
        run: terragrunt --version 

      - name: 'Apply Destroy' # Start task on target, set target desired = 2
        run: |
          cd ./terraform
          echo "yes" | terragrunt destroy -var-file=environment.tfvars -var-file=general.tfvars -var mode=both -var tasks=both 